apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nginx-shared-data
    namespace: miro-test
spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Mi
    volumeMode: Filesystem
    storageClassName: "standard"